---
- name: Ensure systemd-timesyncd configuration
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart timesyncd

- name: Enable time synchronization
  command: timedatectl set-ntp true
